apiVersion: v1
kind: Service
metadata:
  name: gassikialaw-en-svc
  namespace: gassikialaw
spec:
  selector:
    app: gassikialaw-en
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30384
  type: NodePort
