apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: en-service-patch.yaml
    target:
      kind: Service
      name: gassikialaw-en-svc
  - path: fr-service-patch.yaml
    target:
      kind: Service
      name: gassikialaw-fr-svc

namespace: gassikialaw

images:
  - name: idrisniyi94/gassikialaw-en
    newTag: IMAGE_TAG
  - name: idrisniyi94/gassikialaw-fr
    newName:  idrisniyi94/gassikialaw-fr
    newTag: IMAGE_TAG

namePrefix: prod-
labels:
  - includeSelectors: true
    pairs:
      env: prod
