apiVersion: apps/v1
kind: Deployment
metadata:
  name: gassikialaw-fr-deployment
  namespace: gassikialaw
spec:
  selector:
    matchLabels:
      app: gassikialaw-fr
  template:
    metadata:
      labels:
        app: gassikialaw-fr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: custom-label
                    operator: In
                    values:
                      - k8s
      containers:
      - name: gassikialaw-fr
        image: idrisniyi94/gassikialaw-fr:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: EMAIL
            value: apikey
          - name: PORT
            value: "465"
          - name: SERVER
            value: smtp.sendgrid.net
          - name:  SERVER_PASS
            valueFrom:
              secretKeyRef:
                name:  smtp-password
                key:  password
