apiVersion: v1
kind: Service
metadata:
  name: gassikialaw-fr-svc
  namespace: gassikialaw
spec:
  selector:
    app: gassikialaw-fr
  ports:
  - port: 5000
    targetPort: 5000
    # nodePort: 31936
  type: NodePort
